#############################################################################
# Makefile for building: bin/release/Laycan.app/Contents/MacOS/Laycan
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  Laycan.pro
# Template: app
# Command: /Users/Anderson/Qt5.5.0/5.5/clang_64/bin/qmake -o Makefile Laycan.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers -I../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers -I../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers -I../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers -Ibin/release/.moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -Ibin/release/.u -I../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang -F/Users/Anderson/Qt5.5.0/5.5/clang_64/lib
QMAKE         = /Users/Anderson/Qt5.5.0/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Laycan1.0.0
DISTDIR = /Users/Anderson/Worksapce/Laycan/bin/release/.obj/Laycan1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/Anderson/Qt5.5.0/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Anderson/Qt5.5.0/5.5/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtSql -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = bin/release/.obj/

####### Files

SOURCES       = lib/SQL.cpp \
		lib/tools.cpp \
		src/connection.cpp \
		src/databaseconfig.cpp \
		src/dictionary.cpp \
		src/dictxml.cpp \
		src/inifile.cpp \
		src/main.cpp \
		src/migrationprogress.cpp bin/release/.qrc/qrc_Resources.cpp \
		bin/release/.moc/moc_connection.cpp \
		bin/release/.moc/moc_databaseconfig.cpp \
		bin/release/.moc/moc_migrationprogress.cpp
OBJECTS       = bin/release/.obj/SQL.o \
		bin/release/.obj/tools.o \
		bin/release/.obj/connection.o \
		bin/release/.obj/databaseconfig.o \
		bin/release/.obj/dictionary.o \
		bin/release/.obj/dictxml.o \
		bin/release/.obj/inifile.o \
		bin/release/.obj/main.o \
		bin/release/.obj/migrationprogress.o \
		bin/release/.obj/qrc_Resources.o \
		bin/release/.obj/moc_connection.o \
		bin/release/.obj/moc_databaseconfig.o \
		bin/release/.obj/moc_migrationprogress.o
DIST          = ../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf \
		Laycan.pro lib/SQL.h \
		lib/tools.h \
		src/connection.h \
		src/databaseconfig.h \
		src/dictionary.h \
		src/dictxml.h \
		src/inifile.h \
		src/ui_databaseconfig.h \
		src/migrationprogress.h lib/SQL.cpp \
		lib/tools.cpp \
		src/connection.cpp \
		src/databaseconfig.cpp \
		src/dictionary.cpp \
		src/dictxml.cpp \
		src/inifile.cpp \
		src/main.cpp \
		src/migrationprogress.cpp
QMAKE_TARGET  = Laycan
DESTDIR       = bin/release/#avoid trailing-slash linebreak
TARGET        = bin/release/Laycan.app/Contents/MacOS/Laycan

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): bin/release/.u/ui_databaseconfig.h bin/release/.u/ui_migrationprogress.h $(OBJECTS)  
	@test -d bin/release/Laycan.app/Contents/MacOS/ || mkdir -p bin/release/Laycan.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Laycan.pro ../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf \
		Laycan.pro \
		resources/Resources.qrc \
		/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtSql.framework/QtSql.prl \
		/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtXml.framework/QtXml.prl \
		/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Laycan.pro
../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf:
../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf:
Laycan.pro:
resources/Resources.qrc:
/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtSql.framework/QtSql.prl:
/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtXml.framework/QtXml.prl:
/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Laycan.pro

qmake_all: FORCE

bin/release/Laycan.app/Contents/PkgInfo: 
	@test -d bin/release/Laycan.app/Contents || mkdir -p bin/release/Laycan.app/Contents
	@$(DEL_FILE) bin/release/Laycan.app/Contents/PkgInfo
	@echo "APPL????" > bin/release/Laycan.app/Contents/PkgInfo
bin/release/Laycan.app/Contents/Resources/empty.lproj: 
	@test -d bin/release/Laycan.app/Contents/Resources || mkdir -p bin/release/Laycan.app/Contents/Resources
	@touch bin/release/Laycan.app/Contents/Resources/empty.lproj
	
bin/release/Laycan.app/Contents/Info.plist: 
	@test -d bin/release/Laycan.app/Contents || mkdir -p bin/release/Laycan.app/Contents
	@$(DEL_FILE) bin/release/Laycan.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Laycan,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Laycan,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >bin/release/Laycan.app/Contents/Info.plist

all: Makefile \
		bin/release/Laycan.app/Contents/PkgInfo \
		bin/release/Laycan.app/Contents/Resources/empty.lproj \
		bin/release/Laycan.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/Resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents lib/SQL.h lib/tools.h src/connection.h src/databaseconfig.h src/dictionary.h src/dictxml.h src/inifile.h src/ui_databaseconfig.h src/migrationprogress.h $(DISTDIR)/
	$(COPY_FILE) --parents lib/SQL.cpp lib/tools.cpp src/connection.cpp src/databaseconfig.cpp src/dictionary.cpp src/dictxml.cpp src/inifile.cpp src/main.cpp src/migrationprogress.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/databaseconfig.ui src/migrationprogress.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r bin/release/Laycan.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: bin/release/.qrc/qrc_Resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) bin/release/.qrc/qrc_Resources.cpp
bin/release/.qrc/qrc_Resources.cpp: resources/Resources.qrc \
		resources/Migrations/note.xml \
		resources/icons/LogOut.png \
		resources/icons/edit_add.png \
		resources/icons/reload.png \
		resources/icons/edit_remove.png \
		resources/icons/package_settings.png \
		resources/icons/edit.png \
		resources/icons/share.png \
		resources/icons/Ok.png \
		resources/icons/1444503647_mysql-2048-black.png \
		resources/icons/vcard.png \
		resources/icons/Cancel.png \
		resources/icons/kdmconfig.png \
		resources/icons/Password.png \
		resources/icons/viewmag.png \
		resources/icons/ClientAdd.png
	/Users/Anderson/Qt5.5.0/5.5/clang_64/bin/rcc -name Resources resources/Resources.qrc -o bin/release/.qrc/qrc_Resources.cpp

compiler_moc_header_make_all: bin/release/.moc/moc_connection.cpp bin/release/.moc/moc_databaseconfig.cpp bin/release/.moc/moc_migrationprogress.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) bin/release/.moc/moc_connection.cpp bin/release/.moc/moc_databaseconfig.cpp bin/release/.moc/moc_migrationprogress.cpp
bin/release/.moc/moc_connection.cpp: ../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		src/inifile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		src/connection.h
	/Users/Anderson/Qt5.5.0/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Anderson/Qt5.5.0/5.5/clang_64/mkspecs/macx-clang -I/Users/Anderson/Worksapce/Laycan -I/Users/Anderson/Worksapce/Laycan -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/Anderson/Qt5.5.0/5.5/clang_64/lib src/connection.h -o bin/release/.moc/moc_connection.cpp

bin/release/.moc/moc_databaseconfig.cpp: ../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/QDomElement \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/qdom.h \
		src/inifile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		src/databaseconfig.h
	/Users/Anderson/Qt5.5.0/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Anderson/Qt5.5.0/5.5/clang_64/mkspecs/macx-clang -I/Users/Anderson/Worksapce/Laycan -I/Users/Anderson/Worksapce/Laycan -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/Anderson/Qt5.5.0/5.5/clang_64/lib src/databaseconfig.h -o bin/release/.moc/moc_databaseconfig.cpp

bin/release/.moc/moc_migrationprogress.cpp: ../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/migrationprogress.h
	/Users/Anderson/Qt5.5.0/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Anderson/Qt5.5.0/5.5/clang_64/mkspecs/macx-clang -I/Users/Anderson/Worksapce/Laycan -I/Users/Anderson/Worksapce/Laycan -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers -I/Users/Anderson/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/Anderson/Qt5.5.0/5.5/clang_64/lib src/migrationprogress.h -o bin/release/.moc/moc_migrationprogress.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: bin/release/.u/ui_databaseconfig.h bin/release/.u/ui_migrationprogress.h
compiler_uic_clean:
	-$(DEL_FILE) bin/release/.u/ui_databaseconfig.h bin/release/.u/ui_migrationprogress.h
bin/release/.u/ui_databaseconfig.h: src/databaseconfig.ui
	/Users/Anderson/Qt5.5.0/5.5/clang_64/bin/uic src/databaseconfig.ui -o bin/release/.u/ui_databaseconfig.h

bin/release/.u/ui_migrationprogress.h: src/migrationprogress.ui
	/Users/Anderson/Qt5.5.0/5.5/clang_64/bin/uic src/migrationprogress.ui -o bin/release/.u/ui_migrationprogress.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

bin/release/.obj/SQL.o: lib/SQL.cpp lib/sql.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QSqlError \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/SQL.o lib/SQL.cpp

bin/release/.obj/tools.o: lib/tools.cpp lib/tools.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/tools.o lib/tools.cpp

bin/release/.obj/connection.o: src/connection.cpp ../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QAbstractButton \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QSqlDriver \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		src/connection.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		src/inifile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		lib/tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/connection.o src/connection.cpp

bin/release/.obj/databaseconfig.o: src/databaseconfig.cpp ../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/QtXml \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/qdom.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/qxml.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		src/databaseconfig.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/QDomElement \
		src/inifile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		src/ui_databaseconfig.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QAction \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QButtonGroup \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QHeaderView \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		lib/tools.h \
		src/dictxml.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		src/dictionary.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		src/migrationprogress.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/connection.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/databaseconfig.o src/databaseconfig.cpp

bin/release/.obj/dictionary.o: src/dictionary.cpp ../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		src/connection.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		src/inifile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		src/dictionary.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		src/dictxml.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/qdom.h \
		lib/tools.h \
		src/migrationprogress.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/dictionary.o src/dictionary.cpp

bin/release/.obj/dictxml.o: src/dictxml.cpp ../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		src/dictionary.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../Qt5.5.0/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		src/dictxml.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/qdom.h \
		lib/tools.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		src/migrationprogress.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/dictxml.o src/dictxml.cpp

bin/release/.obj/inifile.o: src/inifile.cpp ../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		src/inifile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/inifile.o src/inifile.cpp

bin/release/.obj/main.o: src/main.cpp ../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		src/databaseconfig.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/QDomElement \
		../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers/qdom.h \
		src/inifile.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/main.o src/main.cpp

bin/release/.obj/migrationprogress.o: src/migrationprogress.cpp src/migrationprogress.h \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		bin/release/.u/ui_migrationprogress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/migrationprogress.o src/migrationprogress.cpp

bin/release/.obj/qrc_Resources.o: bin/release/.qrc/qrc_Resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/qrc_Resources.o bin/release/.qrc/qrc_Resources.cpp

bin/release/.obj/moc_connection.o: bin/release/.moc/moc_connection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/moc_connection.o bin/release/.moc/moc_connection.cpp

bin/release/.obj/moc_databaseconfig.o: bin/release/.moc/moc_databaseconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/moc_databaseconfig.o bin/release/.moc/moc_databaseconfig.cpp

bin/release/.obj/moc_migrationprogress.o: bin/release/.moc/moc_migrationprogress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/release/.obj/moc_migrationprogress.o bin/release/.moc/moc_migrationprogress.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

