#ifndef LAYCANEDITOR_GLOBAL_H
#define LAYCANEDITOR_GLOBAL_H

#include <QtGlobal>

#if defined(LAYCANEDITOR_LIBRARY)
#  define LAYCANEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LAYCANEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LAYCANEDITOR_GLOBAL_H

